AppBundle\Entity\FspOutDivisions:
    type: entity
    table: fsp_out_divisions
    repositoryClass: AppBundle\Entity\FspOutDivisionsRepository
    id:
        gameid:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
        drawnr:
            type: integer
            nullable: true
            options:
                unsigned: false
        divnr:
            type: integer
            nullable: true
            options:
                unsigned: false
    fields:
        winnersq:
            type: decimal
            nullable: false
        winnersamount:
            type: decimal
            nullable: false
    lifecycleCallbacks: {  }
