AppBundle\Entity\TblGamesByDate:
    type: entity
    table: tbl_games_by_date
    repositoryClass: AppBundle\Entity\TblGamesByDateRepository
    id:
        gameid:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
        drawnr:
            type: integer
            nullable: true
            options:
                unsigned: false
    fields:
        drawdate:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
