<?php

namespace AppBundle\Entity;

/**
 * Fsp_GamesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Fsp_GamesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getGamesByDate($gameId,$gameDate) {
		$query = $this->getEntityManager()
		              ->createQuery ( 
		              		"select g 
        	                   from AppBundle:Fsp_Games g
                              where g.gameId = :gameId
		              		    and g.gameDateTime = :gameDate
		              		  order by g.drawNr desc,g.winningNr")
		              ->setParameter ( "gameId", $gameId )
		              ->setParameter ( "gameDate", $gameDate );
		try {
			return $query->getResult();
		} catch ( \Doctrine\ORM\NoResultException $e ) {
			return null;
		}
	}
	public function getGamesByDate($gameId,$gameDate) {
	}
	}
}
