<?php

namespace AppBundle\Entity;

/**
 * FspInpHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FspInpHeaderRepository extends \Doctrine\ORM\EntityRepository {
	public function findGamesByDate($gameId, $gameDate) {
		$query = $this->getEntityManager ()
		              ->createQuery ( 
		              		"select h 
                               from AppBundle:FspInpHeader h
                              where h.gameid   = :gameid
                                and h.drawdate = :gamedate
                              order by h.drawnr" )
		              ->setParameter ( "gameid", $gameId )
		              ->setParameter ( "gamedate", $gameDate );
		$data = $query->getResult();
		$ret = array();
		foreach ( $data as $row ){
			$ret[] = $row->getDrawnr();
		}
		return $ret;
	}
}
