<?php

namespace AppBundle\Entity;

/**
 * FspOutDivisionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FspOutDivisionsRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDivList($gameId,$drawNr) {
		$query = $this->getEntityManager ()
		               ->createQuery (
				            "select od
                               from AppBundle:FspOutDivisions od
                              where od.gameid = :gameid
                                and od.drawnr = :drawnr
                              order by od.divnr" )
		               ->setParameter ( "gameid", $gameId )
		               ->setParameter ( "drawnr", $drawNr );
		$data = $query->getResult();
        $ret = array();
		foreach ( $data as $row ){
			$ret[] = array(
						"divNr" => $row->getDivnr(),
                        "divAm" => $row->getWinnersamount()
					 );
		}
		return $ret;		
	}
	
}
