<?php



namespace AppBundle\Entity;

use \AppBundle\Util\GameFactory;
use \AppBundle\Util\GameHelper;

/**
 * TblGamesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblGamesRepository extends \Doctrine\ORM\EntityRepository {

	public function newGameInstance($gameId) {
		// Forced!
		// In a new incarnation, must be dynamic
		$em = $this->getEntityManager();
		if ( $gameId === "E" )
			return new Elegi2($em);
		if ( $gameId === "P" )
			return new Premio($em);
		if ( $gameId === "S" )
			return new SuperLotto($em);
		
		return null;
	}



    public function getGamesByDate($gameId,$gameDate) {

        $game = $this->newGameInstance($gameId);
        $lastGame = $game->getLastGame();

        if ( $gameDate > $lastGame["drawdate"] ) {
            //$this->loadGamesByDateFromWS($gameId,$gameDate);
        }

        return $game->getGamesByDate($gameDate);

    }

}
