<?php

namespace AppBundle\Entity;

use \AppBundle\Util\GameFactory;

/**
 * TblStakesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblStakesRepository extends \Doctrine\ORM\EntityRepository
{
  public function getStakes() {
    $retVal = [];
    foreach ( GameFactory::getGameList() as $game ) {
      $gameObj = new $game;
      $gameId = $gameObj->getGameId();
      $retVal[$gameId] = $this->getGameStakes($gameId);
    }
    return $retVal;
  }  

  public function getGameStakes($gameId) {
      $query = $this->getEntityManager()
                    ->createQuery (
                          "select s
                             from AppBundle:TblStakes s
                            where s.gameid = :gameid" )
                    ->setParameter ( "gameid", $gameId );
      try  {
      	$data = $query->getSingleResult();
        return json_decode($data->getStakes());
      } catch (\Exception $ex) {
      	return null;
      }
  }

  
}
